sudo: required

language: node_js
node_js:
  - "5"

services:
  - docker

install:
  - cd server/ && npm install && cd ..

script:
  - cd server/ && npm test && cd ..
  - docker build -t dollarshaveclub/fastboot-docker .
